- name: My first play
  hosts: hosts
  tasks:
   - name: Ping my hosts
     ping:
   - name: Print message
     debug:
       msg: Hello world
   - name: update host
     command:
       cmd: sudo yum update -y
   - name: print again
     debug:
       msg: hello
   - name: create directory
     file:
       path: /home/ec2-user/mary
       state: directory